src/Entity/Desempenyo/Evalua.php
<?php

namespace App\Entity\Desempenyo;

use App\Entity\Cuestiona\Cuestionario;
use App\Entity\Cuestiona\Formulario;
use App\Entity\Plantilla\Empleado;
use App\Entity\Usuario;
use App\Repository\Desempenyo\EvaluaRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * Entidad para gestionar permisos de evaluación de desempeño (relación evaluador y empleado evaluado).
 * @author Ramón M. Gómez <ramongomez@us.es>
 */
#[ORM\Entity(repositoryClass: EvaluaRepository::class)]
#[ORM\Table(name: 'desempenyo_evalua')]
#[ORM\Index(
    columns: ['cuestionario_id', 'empleado_id', 'evaluador_id'],
    name: 'desempenyo_cuestionario_empleado_evaluador_idx'
)]
class Evalua
{
    final public const string MANUAL = 'MANUAL';    // Edición manual en el propio sistema
    final public const string SSO = 'SSO';  // Acceso por SSO
    final public const string EXTERNO = 'EXTERNO';  // Carga de datos desde sistema externo
    final public const string FICHERO = 'FICHERO';  // Carga de datos desde fichero

    // Tipos de evaluaciones
    public const int NO_EVALUACION = 0; // Solicitud de no evaluación

    public const int AUTOEVALUACION = 1;    // Autoevaluación

    public const int EVALUA_RESPONSABLE = 2;    // Evaluación por el responsable

    public const int EVALUA_OTRO = 3;   // Evaluación por otro agente

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Empleado::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?Empleado $empleado = null;

    #[ORM\ManyToOne(targetEntity: Empleado::class)]
    private ?Empleado $evaluador = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: false, options: ['default' => 1])]
    private int $tipo_evaluador = self::AUTOEVALUACION;

    #[ORM\ManyToOne(targetEntity: Cuestionario::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cuestionario $cuestionario = null;

    #[ORM\ManyToOne(targetEntity: Formulario::class)]
    private ?Formulario $formulario = null;

    /** @var DateTimeImmutable|null $rechazado Fecha que el usuario solicitó rechazar su evaluación */
    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?DateTimeImmutable $rechazado = null;

    /** @var string|null $rechazo_texto Texto descriptivo del rechazo en Registro General */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $rechazo_texto = null;

    /** @var DateTimeImmutable|null $registrado Fecha en que el rechazo entra en Registro General */
    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?DateTimeImmutable $registrado = null;

    /** @var float|null $correccion Corrección de puntuación global de un empleado por parte del tribunal */
    #[ORM\Column(type: Types::FLOAT, nullable: true)]
    private ?float $correccion = null;

    /** @var string|null $comentario Comentario sobre la corrección de la puntuación global */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $comentario = null;

    /** @var Usuario|null $corrector Usuario que añade la corrección global */
    #[ORM\ManyToOne(targetEntity: Usuario::class)]
    private ?Usuario $corrector = null;

    /** @var DateTimeImmutable|null $corregido Fecha en que se hace la corrección global */
    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?DateTimeImmutable $corregido = null;

    /** @var bool $habilita Indica si el usuario habilita su autoevaluación */
    #[ORM\Column(type: Types::BOOLEAN, nullable: false, options: ['default' => 0])]
    private bool $habilita = false;

    /** @var string|null $origen Origen de los datos guardados */
    #[ORM\Column(type: Types::STRING, length: 10)]
    private ?string $origen = null;

    /** @var string|null $testimonio Comentario de evaluación apoyada en testimonio de otro responsable */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $testimonio = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmpleado(): ?Empleado
    {
        return $this->empleado;
    }

    public function setEmpleado(?Empleado $empleado): static
    {
        $this->empleado = $empleado;

        return $this;
    }

    public function getEvaluador(): ?Empleado
    {
        return $this->evaluador;
    }

    public function setEvaluador(?Empleado $evaluador): static
    {
        $this->evaluador = $evaluador;

        return $this;
    }

    public function getTipoEvaluador(): int
    {
        return $this->tipo_evaluador;
    }

    public function setTipoEvaluador(int $tipo = self::AUTOEVALUACION): static
    {
        $this->tipo_evaluador = $tipo;

        return $this;
    }

    public function getCuestionario(): ?Cuestionario
    {
        return $this->cuestionario;
    }

    public function setCuestionario(?Cuestionario $cuestionario): static
    {
        $this->cuestionario = $cuestionario;

        return $this;
    }

    public function getFormulario(): ?Formulario
    {
        return $this->formulario;
    }

    public function setFormulario(?Formulario $formulario): static
    {
        $this->formulario = $formulario;

        return $this;
    }

    public function getRechazado(): ?DateTimeImmutable
    {
        return $this->rechazado;
    }

    public function setRechazado(?DateTimeImmutable $fecha): static
    {
        $this->rechazado = $fecha;

        return $this;
    }

    public function getRechazoTexto(): ?string
    {
        return $this->rechazo_texto;
    }

    public function setRechazoTexto(?string $texto): static
    {
        $this->rechazo_texto = $texto;

        return $this;
    }

    public function getRegistrado(): ?DateTimeImmutable
    {
        return $this->registrado;
    }

    public function setRegistrado(?DateTimeImmutable $fecha): static
    {
        $this->registrado = $fecha;

        return $this;
    }

    public function getCorreccion(): ?float
    {
        return $this->correccion;
    }

    public function setCorreccion(?float $puntuacion): static
    {
        $this->correccion = $puntuacion;

        return $this;
    }

    public function getComentario(): ?string
    {
        return $this->comentario;
    }

    public function setComentario(?string $comentario): static
    {
        $this->comentario = $comentario;

        return $this;
    }

    public function getCorrector(): ?Usuario
    {
        return $this->corrector;
    }

    public function setCorrector(?Usuario $corrector): static
    {
        $this->corrector = $corrector;

        return $this;
    }

    public function getCorregido(): ?DateTimeImmutable
    {
        return $this->corregido;
    }

    public function setCorregido(?DateTimeImmutable $fecha): static
    {
        $this->corregido = $fecha;

        return $this;
    }

    public function isHabilita(): bool
    {
        return $this->habilita;
    }

    public function setHabilita(bool $habilita = true): static
    {
        $this->habilita = $habilita;

        return $this;
    }

    public function getOrigen(): ?string
    {
        return $this->origen;
    }

    public function setOrigen(?string $origen): static
    {
        $this->origen = $origen;

        return $this;
    }

    public function getTestimonio(): ?string
    {
        return $this->testimonio;
    }

    public function setTestimonio(?string $testimonio): static
    {
        $this->testimonio = $testimonio;

        return $this;
    }
}

src/Controller/Desempenyo/CuestionarioController.php
<?php

namespace App\Controller\Desempenyo;

use App\Entity\Cuestiona\Cuestionario;
use App\Entity\Estado;
use App\Entity\Usuario;
use App\Form\Cuestiona\CuestionarioType;
use App\Form\Cuestiona\PeriodoValidezType;
use App\Form\Desempenyo\CuestionarioFechasType;
use App\Form\Desempenyo\CuestionarioPesosType;
use App\Repository\Cuestiona\CuestionarioRepository;
use App\Repository\EstadoRepository;
use App\Service\MessageGenerator;
use App\Service\Slug;
use DateTimeImmutable;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

/**
 * Controlador para gestionar cuestionarios para evaluación de desempeño.
 * @author Ramón M. Gómez <ramongomez@us.es>
 */
#[Route(path: '/desempenyo/admin/cuestionario', name: 'desempenyo_admin_cuestionario_')]
class CuestionarioController extends AbstractController
{
    public function __construct(
        private readonly MessageGenerator       $generator,
        private readonly CuestionarioRepository $cuestionarioRepository,
    ) {
    }

    #[Route(
        path: '/',
        name: 'index',
        defaults: ['titulo' => 'Cuestionarios de Evaluación de Desempeño'],
        methods: ['GET']
    )]
    public function index(EstadoRepository $estadoRepository): Response
    {
        $this->denyAccessUnlessGranted('admin');

        return $this->render('desempenyo/admin/cuestionario/index.html.twig', [
            'cuestionarios' => $this->cuestionarioRepository->findAll(),
            'estados' => $estadoRepository->findBy(['tipo' => Estado::SISTEMA]),
        ]);
    }

    #[Route(
        path: '/new',
        name: 'new',
        defaults: ['titulo' => 'Nuevo Cuestionario de Evaluación de Desempeño'],
        methods: ['GET', 'POST']
    )]
    public function new(Request $request, EstadoRepository $estadoRepository): Response
    {
        $this->denyAccessUnlessGranted('admin');
        /** @var Usuario $autor */
        $autor = $this->getUser();
        $cuestionario = new Cuestionario();
        $cuestionario
            ->setEstado($estadoRepository->findOneBy(['nombre' => Estado::BORRADOR]))
            ->setAutor($autor)
        ;
        $form = $this->createForm(CuestionarioType::class, $cuestionario, [
            'de_aplicacion' => true,
            'con_fechas' => true,
            'form_configuracion' => CuestionarioPesosType::class,
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->cuestionarioRepository->save($cuestionario, true);
            $this->generator->logAndFlash('info', 'Nuevo cuestionario de desempeño', [
                'id' => $cuestionario->getId(),
                'codigo' => $cuestionario->getCodigo(),
            ]);

            return $this->redirectToRoute('desempenyo_admin_cuestionario_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('desempenyo/admin/cuestionario/new.html.twig', [
            'cuestionario' => $cuestionario,
            'form' => $form->createView(),
        ]);
    }

    #[Route(
        path: '/{id}',
        name: 'show',
        defaults: ['titulo' => 'Cuestionario de Evaluación de Desempeño'],
        methods: ['GET']
    )]
    public function show(Cuestionario $cuestionario): Response
    {
        $this->denyAccessUnlessGranted('admin');

        return $this->render('desempenyo/admin/cuestionario/show.html.twig', [
            'cuestionario' => $cuestionario,
        ]);
    }

    #[Route(
        path: '/{id}/edit',
        name: 'edit',
        defaults: ['titulo' => 'Editar Cuestionario de Evaluación de Desempeño'],
        methods: ['GET', 'POST']
    )]
    public function edit(Request $request, Cuestionario $cuestionario): Response
    {
        $this->denyAccessUnlessGranted('admin');
        if (Estado::BORRADOR !== $cuestionario->getEstado()?->getNombre()) {
            $this->addFlash('warning', 'El cuestionario no puede ser editado porque no es un borrador.');

            return $this->redirectToRoute('desempenyo');
        }

        $form = $this->createForm(CuestionarioType::class, $cuestionario, [
            'de_aplicacion' => true,
            'con_fechas' => true,
            'form_configuracion' => CuestionarioPesosType::class,
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Usuario $autor */
            $autor = $this->getUser();
            $cuestionario->setAutor($autor);
            $this->cuestionarioRepository->save($cuestionario, true);
            $this->generator->logAndFlash('info', 'Cuestionario de desempeño modificado', [
                'id' => $cuestionario->getId(),
                'codigo' => $cuestionario->getCodigo(),
            ]);

            return $this->redirectToRoute('desempenyo_admin_cuestionario_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('desempenyo/admin/cuestionario/edit.html.twig', [
            'cuestionario' => $cuestionario,
            'form' => $form->createView(),
        ]);
    }

    #[Route(
        path: '/{id}/delete',
        name: 'delete',
        defaults: ['titulo' => 'Eliminar Cuestionario de Evaluación de Desempeño'],
        methods: ['GET', 'POST']
    )]
    public function delete(Request $request, Cuestionario $cuestionario): Response
    {
        $this->denyAccessUnlessGranted('admin');
        $id = $cuestionario->getId();
        if (count($cuestionario->getGrupos()) > 0) {
            $this->generator->logAndFlash('error', 'No se puede eliminar un cuestionario con grupos definidos.', [
                'id' => $id,
                'codigo' => $cuestionario->getCodigo(),
            ]);
        } elseif ($this->isCsrfTokenValid('delete' . (int) $id, $request->request->getString('_token'))) {
            $this->cuestionarioRepository->remove($cuestionario, true);
            $this->generator->logAndFlash('info', 'Cuestionario eliminado', [
                'id' => $id,
                'codigo' => $cuestionario->getCodigo(),
            ]);
        }

        return $this->redirectToRoute('desempenyo_admin_cuestionario_index', [], Response::HTTP_SEE_OTHER);
    }

    /** Activar formulario (estado publicado). */
    #[Route(
        path: '/{id}/activar',
        name: 'activar',
        defaults: ['titulo' => 'Activar Cuestionario'],
        methods: ['GET', 'POST']
    )]
    public function activar(Request $request, EstadoRepository $estadoRepository, Cuestionario $cuestionario): Response
    {
        $this->denyAccessUnlessGranted('admin');
        if (0 === count($cuestionario->getGrupos())) {
            $this->addFlash('warning', 'El cuestionario no tiene preguntas definidas.');

            return $this->redirectToRoute('desempenyo_admin_cuestionario_show', ['id' => $cuestionario->getId()]);
        } elseif ($cuestionario->getGrupos()->filter(static fn ($grupo) => count($grupo->getPreguntas()) === 0)->count() > 0) {
            $this->addFlash('warning', 'El cuestionario tiene algún grupo de preguntas vacío.');

            return $this->redirectToRoute('desempenyo_admin_cuestionario_show', ['id' => $cuestionario->getId()]);
        }

        $form = $this->createForm(PeriodoValidezType::class, $cuestionario, [
            'con_fechas' => true,
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if (!$cuestionario->getFechaAlta() instanceof DateTimeImmutable
                || !$cuestionario->getFechaBaja() instanceof DateTimeImmutable) {
                $this->addFlash('warning', 'Las fechas inicial y final son obligatorias.');

                return $this->redirectToRoute($request->attributes->getString('_route'), [
                    'id' => $cuestionario->getId(),
                ]);
            } elseif ($cuestionario->getFechaAlta() > $cuestionario->getFechaBaja()) {
                $this->addFlash('warning', 'La fecha final debe ser posterior o igual a la fecha inicial.');

                return $this->redirectToRoute($request->attributes->getString('_route'), [
                    'id' => $cuestionario->getId(),
                ]);
            }

            $publicado = $estadoRepository->findOneBy(['nombre' => Estado::PUBLICADO]);
            $url = $cuestionario->getUrl() ?? sprintf(
                '/desempenyo/formulario/%s-%s',
                (new Slug())((string) $cuestionario->getCodigo()),
                uniqid()
            );
            $cuestionario
                ->setEstado($publicado)
                ->setUrl($url)
            ;
            $this->cuestionarioRepository->save($cuestionario, true);
            $this->generator->logAndFlash('info', 'Cuestionario activado', [
                'id' => $cuestionario->getId(),
                'codigo' => $cuestionario->getCodigo(),
            ]);

            return $this->render('desempenyo/admin/cuestionario/activo.html.twig', [
                'cuestionario' => $cuestionario,
            ]);
        }

        return $this->render('desempenyo/admin/cuestionario/edit.html.twig', [
            'cuestionario' => $cuestionario,
            'activar' => $cuestionario->getEstado()?->getNombre() === Estado::BORRADOR,
            'form' => $form->createView(),
        ]);
    }

    /** Desactivar formulario (estado borrador). */
    #[Route(
        path: '/{id}/desactivar',
        name: 'desactivar',
        defaults: ['titulo' => 'Desactivar Cuestionario'],
        methods: ['GET']
    )]
    public function desactivar(EstadoRepository $estadoRepository, Cuestionario $cuestionario): Response
    {
        $this->denyAccessUnlessGranted('admin');
        $cuestionario->setEstado($estadoRepository->findOneBy(['nombre' => Estado::BORRADOR]));
        $this->cuestionarioRepository->save($cuestionario, true);

templates/desempenyo/_index_desarrollo.html.twig
<div class="pagina-seccion">Área de desarrollo profesional</div>

<div class="container-fluid my-2">
    <ul class="lead my-3">
        {% if not registrado -%}
            <li>
                <a href="{{ activos[0].url ~ '/compara' }}">Oportunidades de alineación de expectativas</a>
            </li>
        {%- endif %}
    </ul>
</div>

templates/desempenyo/_index_documentos.html.twig
<div class="pagina-seccion" id="documentos">Documentos y enlaces de interés del procedimiento activo</div>

<ul class="lead my-3">
    <li>Texto del acuerdo</li>
    <li>Escalas Lickert</li>
    <li>Cuestionario (PDF y Word)</li>
    <li>Enlaces de interés a procedimientos electrónicos
        (presentación de instancias, interposición de recursos administrativos, ...)
    </li>
</ul>

templates/desempenyo/_index_fase3.html.twig
<div class="pagina-seccion">
    Fase 3: Evaluación por parte de otras personas evaluadoras colaboradoras
    ({{ activos[0].configuracion.peso3|default(pesos[2]) }}%)
</div>

<div class="container-fluid my-2">
    <a data-bs-toggle="collapse" href="#acordeonOtro" aria-expanded="false" aria-controls="acordeonOtro">
        <em class="me-2 fas fa-info-circle text-info"></em>
        Pulsar para obtener más detalle del procedimiento.
    </a>
</div>
<div class="collapse" id="acordeonOtro">
    <div class="container-fluid my-2 fw-bold">
        Artículos 9 y 11, y anexo del "Cuestionario de evaluación de competencias profesionales".
    </div>
    <div class="container-fluid my-2">
        En este apartado debe realizar su evaluación como persona evaluadora colaboradora (tercer
        agente, con valor ponderado del {{ activos[0].configuracion.peso3|default(pesos[2]) }}%).
    </div>
    <div class="container-fluid my-2">
        El cuestionario deberá ser valorado aplicando una escala Likert de 1 a 10 (siendo 1 el valor
        mínimo y 10 el valor máximo).
    </div>
    <div class="container-fluid my-2">
        Para los valores comprendidos en el intervalo <strong>de 5 a 7, no es obligatorio</strong>
        indicar evidencias.
    </div>
    <div class="container-fluid my-2">
        Para los valores comprendidos en los intervalos de 1 a 4, y de 8 a 10, todos los agentes
        evaluadores deberán indicar una o varias evidencias específicas que sirvan de justificación del
        valor otorgado a esta.
    </div>
    <div class="container-fluid my-2">
        En caso de que la evidencia o conducta específica señalada no se considere adecuada como
        justificación del valor numérico otorgado, este podrá no ser tenido en cuenta en el resultado de
        la evaluación en el supuesto de desviación de las puntuaciones en más de 5 puntos entre las
        otorgadas por la persona responsable y la autoevaluación.
    </div>
    <div class="container-fluid my-2">
        Para más detalle sobre los criterios de valoración a aplicar por cada intervalo de valores de
        1 a 4, de 5 a 8 y de 9 a 10, consultar el cuestionario facilitado en
        <a class="activarTab" href="" data-bs-target="#vert-tabs-documentos-tab">documentos de interés</a>.
    </div>
</div>
<ul class="lead my-3">
    {%- if activos[0].fechaAlta|date('Ymd') <= hoy and hoy <= activos[0].fechaBaja|date('Ymd') %}
        <li>
            <a class="fw-bold"
               href="{{ activos[0].url ~ '/empleado?tipo=' ~ constant('App\\Entity\\Desempenyo\\Evalua::EVALUA_OTRO') }}">
                Comprobar relación de personas a evaluar y realizar o consultar sus evaluaciones
            </a>
        </li>
    {%- endif %}
</ul>

templates/desempenyo/evaluador.html.twig
{% extends 'desempenyo/index.html.twig' %}

{% block content %}
    <div class="pagina-titulo">{{ titulo }}</div>
    <div class="my-4">
        <div>
            En este apartado puede comprobar las personas evaluadoras y sus roles asignados:
        </div>
        <ul>
            <li>Rol Responsable/Principal: {{ cuestionario.configuracion.peso2 }} %</li>
            <li>Rol Agente colaborador: {{ cuestionario.configuracion.peso3 }} %</li>
        </ul>
        <div>Si detecta alguna incidencia, puede comunicarla pulsando sobre el botón "Nueva incidencia".</div>
    </div>

    <div class="pagina-seccion">Cuestionario {{ cuestionario.titulo }}</div>
    <div class="my-4">
        {%- if evaluaciones|length == 0 %}
            <div class="alert alert-warning">
            <em class="mx-2 fas fa-exclamation-triangle"></em>
            No tiene evaluadores asignados, puede solicitarlo creando una nueva incidencia.
            </div>
        {%- else %}
            <table class="tabla-condensada" id="datosEvaluadores">
                <thead class="cabecera-condensada">
                    <tr>
                        <th>Unidad</th>
                        <th>Evaluador</th>
                        <th>Rol evaluador</th>
                    </tr>
                </thead>
                <tbody>
                {%- for evaluacion in evaluaciones %}
                    <tr>
                        <td>{{ evaluacion.evaluador.unidad.nombre }}</td>
                        <td>{{ evaluacion.evaluador }}</td>
                        <td>
                            {%- if evaluacion.tipoEvaluador == constant('App\\Entity\\Desempenyo\\Evalua::EVALUA_RESPONSABLE') -%}
                                Responsable/Principal
                            {%- elseif evaluacion.tipoEvaluador == constant('App\\Entity\\Desempenyo\\Evalua::EVALUA_OTRO') -%}
                                Agente colaborador
                            {%- else -%}
                                <span class="badge-warning">Desconocido</span>
                            {%- endif -%}
                        </td>
                    </tr>
                {%- endfor %}
                </tbody>
            </table>
        {%- endif %}
    </div>
{% endblock %}

{% block botones %}
    <li class="nav-item me-2">
        <a class="btn btn-primary" href="{{ path('desempenyo_formulario_incidencia_new', {codigo: cuestionario.url|u.afterLast('/')}) }}">
            <em class="fas fa-ear-listen"></em> Nueva incidencia
        </a>
    </li>
{% endblock %}

{% block migas %}
    {{ parent() }}
    <li class="breadcrumb-item">
        <a href="{{ path('desempenyo') }}"><em class="me-1 fas fa-user-check"></em>Desempeño</a>
    </li>
{% endblock %}

{% block modal %}
{% endblock %}

{% block js %}
    {{ parent() }}
    <script type="module">
        $('#datosEvaluadores').dataTable({
            buttons: [
                {
                    extend: 'copy',
                    text: '<i class="fas fa-copy"></i>',
                    titleAttr: 'Copiar',
                },
                {
                    extend: 'print',
                    text: '<i class="fas fa-print"></i>',
                    titleAttr: 'Imprimir',
                },
                {
                    extend: 'csv',
                    text: '<i class="fas fa-file-csv"></i>',
                    titleAttr: 'Generar fichero CSV',
                },
                {
                    extend: 'excelHtml5',
                    text: '<i class="fas fa-file-excel"></i>',
                    titleAttr: 'Generar fichero Excel',
                },
            ],
            dom: '<"row"<"col-sm-12 col-md-4"B><"col-sm-12 col-md-4"l><"col-sm-12 col-md-4"f>>' +
                '<"row"<"col-sm-12"<"table-responsive"tr>>>' +
                '<"row"<"col-sm-12 col-md-5"i><"col-sm-12 col-md-7"p>>',
            language: {
                url: '{{ asset("includes/datatable.es.json") }}',
            },
        });
    </script>
{% endblock %}

templates/desempenyo/formulario_pdf.html.twig
{% extends '/layout/base_pdf.html.twig' %}

{% block title %}Autoevaluación: {{ evalua.cuestionario.codigo }}{% endblock %}

{% block content %}
{% set tipos_preguntas -%}
    {{ render(controller('App\\Controller\\Cuestiona\\PreguntaController::getTipos')) }}
{%- endset -%}
    <div class="pagina">
        <h2>{{ evalua.cuestionario.titulo }}</h2>
        <div>{{ evalua.cuestionario.descripcion|raw }}</div>
        {%- if evalua.tipoEvaluador == constant('App\\Entity\\Desempenyo\\Evalua::AUTOEVALUACION') %}
            <h3>Autoevaluación de {{ app.user.empleado }}</h3>
        {%- elseif evalua.tipoEvaluador == constant('App\\Entity\\Desempenyo\\Evalua::EVALUA_RESPONSABLE') %}
            <h3>Evaluación de {{ evalua.empleado }} por parte de agente principal {{ app.user.empleado }}</h3>
        {%- elseif evalua.tipoEvaluador == constant('App\\Entity\\Desempenyo\\Evalua::EVALUA_OTRO') %}
            <h3>Evaluación de {{ evalua.empleado }} por parte de tercer agente {{ app.user.empleado }}</h3>
        {%- endif %}
        <dl>
            <dt>Fecha de entrega: {{ evalua.formulario.fechaEnvio|date('d/m/Y') }}</dt>
            {% if evalua.testimonio %}
                <dt>
                    Otras personas responsables y/o colaboradoras cuyos testimonios evidenciados han servido de ayuda o
                    apoyo en este proceso de evaluación:
                </dt>
                <dd>{{ evalua.testimonio }}</dd>
            {% endif %}
        </dl>
    </div>

    {%- for grupo in evalua.cuestionario.grupos|filter(g => g.activa)|sort((a, b) => a.orden <=> b.orden) %}
        <div class="salto-pagina"></div>
        <h5>{{ grupo }}</h5>
        <div>{{ grupo.descripcion|raw }}</div>
        <table class="tabla">
            <thead>
            <tr>
                <th style="width: 50%;">Pregunta</th>
                <th style="width: 10%;">Valoración</th>
                <th style="width: 40%;">Evidencias</th>
            </tr>
            </thead>
            <tbody>
            {%- set puntos = 0 %}
            {%- for pregunta in grupo.preguntas|filter(p => p.activa and not p.reducida)|sort((a, b) => a.orden <=> b.orden) %}
                <tr>
                    <td>{{ pregunta }}</td>
                    <td class="text-end">{{ respuestas[pregunta.id].valor|default }}</td>
                    <td>{{ respuestas[pregunta.id].observa|default }}</td>
                </tr>
                {%- set puntos = puntos + respuestas[pregunta.id].valor|default(0) %}
                {%- if loop.last %}
                    <tr class="ultimo">
                        <td>Media</td>
                        <td class="text-end">{{ (puntos / loop.index)|number_format(2, ',' ) }}</td>
                        <td></td>
                    </tr>
                {%- endif %}
            {%- endfor %}
            </tbody>
        </table>
    {%- endfor %}
{% endblock %}

{% block css %}
    {{ parent() }}
    th {
        padding: 0.2em;
        border-bottom: 1px solid;
        text-align: left;
    }
    td {
        padding: 0.5em;
        vertical-align: top;
    }
    .ultimo td {
        border-top: 1px solid;
    }
{% endblock %}