src/Entity/Desempenyo/Evalua.php
<?php

namespace App\Entity\Desempenyo;

use App\Entity\Cuestiona\Cuestionario;
use App\Entity\Cuestiona\Formulario;
use App\Entity\Plantilla\Empleado;
use App\Entity\Usuario;
use App\Repository\Desempenyo\EvaluaRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * Entidad para gestionar permisos de evaluación de desempeño (relación evaluador y empleado evaluado).
 * @author Ramón M. Gómez <ramongomez@us.es>
 */
#[ORM\Entity(repositoryClass: EvaluaRepository::class)]
#[ORM\Table(name: 'desempenyo_evalua')]
#[ORM\Index(
    columns: ['cuestionario_id', 'empleado_id', 'evaluador_id'],
    name: 'desempenyo_cuestionario_empleado_evaluador_idx'
)]
class Evalua
{
    final public const string MANUAL = 'MANUAL';    // Edición manual en el propio sistema
    final public const string SSO = 'SSO';  // Acceso por SSO
    final public const string EXTERNO = 'EXTERNO';  // Carga de datos desde sistema externo
    final public const string FICHERO = 'FICHERO';  // Carga de datos desde fichero

    // Tipos de evaluaciones
    public const int NO_EVALUACION = 0; // Solicitud de no evaluación

    public const int AUTOEVALUACION = 1;    // Autoevaluación

    public const int EVALUA_RESPONSABLE = 2;    // Evaluación por el responsable

    public const int EVALUA_OTRO = 3;   // Evaluación por otro agente

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(targetEntity: Empleado::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?Empleado $empleado = null;

    #[ORM\ManyToOne(targetEntity: Empleado::class)]
    private ?Empleado $evaluador = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: false, options: ['default' => 1])]
    private int $tipo_evaluador = self::AUTOEVALUACION;

    #[ORM\ManyToOne(targetEntity: Cuestionario::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cuestionario $cuestionario = null;

    #[ORM\ManyToOne(targetEntity: Formulario::class)]
    private ?Formulario $formulario = null;

    /** @var DateTimeImmutable|null $rechazado Fecha que el usuario solicitó rechazar su evaluación */
    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?DateTimeImmutable $rechazado = null;

    /** @var string|null $rechazo_texto Texto descriptivo del rechazo en Registro General */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $rechazo_texto = null;

    /** @var DateTimeImmutable|null $registrado Fecha en que el rechazo entra en Registro General */
    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?DateTimeImmutable $registrado = null;

    /** @var float|null $correccion Corrección de puntuación global de un empleado por parte del tribunal */
    #[ORM\Column(type: Types::FLOAT, nullable: true)]
    private ?float $correccion = null;

    /** @var string|null $comentario Comentario sobre la corrección de la puntuación global */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $comentario = null;

    /** @var Usuario|null $corrector Usuario que añade la corrección global */
    #[ORM\ManyToOne(targetEntity: Usuario::class)]
    private ?Usuario $corrector = null;

    /** @var DateTimeImmutable|null $corregido Fecha en que se hace la corrección global */
    #[ORM\Column(type: Types::DATETIME_IMMUTABLE, nullable: true)]
    private ?DateTimeImmutable $corregido = null;

    /** @var bool $habilita Indica si el usuario habilita su autoevaluación */
    #[ORM\Column(type: Types::BOOLEAN, nullable: false, options: ['default' => 0])]
    private bool $habilita = false;

    /** @var string|null $origen Origen de los datos guardados */
    #[ORM\Column(type: Types::STRING, length: 10)]
    private ?string $origen = null;

    /** @var string|null $testimonio Comentario de evaluación apoyada en testimonio de otro responsable */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $testimonio = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmpleado(): ?Empleado
    {
        return $this->empleado;
    }

    public function setEmpleado(?Empleado $empleado): static
    {
        $this->empleado = $empleado;

        return $this;
    }

    public function getEvaluador(): ?Empleado
    {
        return $this->evaluador;
    }

    public function setEvaluador(?Empleado $evaluador): static
    {
        $this->evaluador = $evaluador;

        return $this;
    }

    public function getTipoEvaluador(): int
    {
        return $this->tipo_evaluador;
    }

    public function setTipoEvaluador(int $tipo = self::AUTOEVALUACION): static
    {
        $this->tipo_evaluador = $tipo;

        return $this;
    }

    public function getCuestionario(): ?Cuestionario
    {
        return $this->cuestionario;
    }

    public function setCuestionario(?Cuestionario $cuestionario): static
    {
        $this->cuestionario = $cuestionario;

        return $this;
    }

    public function getFormulario(): ?Formulario
    {
        return $this->formulario;
    }

    public function setFormulario(?Formulario $formulario): static
    {
        $this->formulario = $formulario;

        return $this;
    }

    public function getRechazado(): ?DateTimeImmutable
    {
        return $this->rechazado;
    }

    public function setRechazado(?DateTimeImmutable $fecha): static
    {
        $this->rechazado = $fecha;

        return $this;
    }

    public function getRechazoTexto(): ?string
    {
        return $this->rechazo_texto;
    }

    public function setRechazoTexto(?string $texto): static
    {
        $this->rechazo_texto = $texto;

        return $this;
    }

    public function getRegistrado(): ?DateTimeImmutable
    {
        return $this->registrado;
    }

    public function setRegistrado(?DateTimeImmutable $fecha): static
    {
        $this->registrado = $fecha;

        return $this;
    }

    public function getCorreccion(): ?float
    {
        return $this->correccion;
    }

    public function setCorreccion(?float $puntuacion): static
    {
        $this->correccion = $puntuacion;

        return $this;
    }

    public function getComentario(): ?string
    {
        return $this->comentario;
    }

    public function setComentario(?string $comentario): static
    {
        $this->comentario = $comentario;

        return $this;
    }

    public function getCorrector(): ?Usuario
    {
        return $this->corrector;
    }

    public function setCorrector(?Usuario $corrector): static
    {
        $this->corrector = $corrector;

        return $this;
    }

    public function getCorregido(): ?DateTimeImmutable
    {
        return $this->corregido;
    }

    public function setCorregido(?DateTimeImmutable $fecha): static
    {
        $this->corregido = $fecha;

        return $this;
    }

    public function isHabilita(): bool
    {
        return $this->habilita;
    }

    public function setHabilita(bool $habilita = true): static
    {
        $this->habilita = $habilita;

        return $this;
    }

    public function getOrigen(): ?string
    {
        return $this->origen;
    }

    public function setOrigen(?string $origen): static
    {
        $this->origen = $origen;

        return $this;
    }

    public function getTestimonio(): ?string
    {
        return $this->testimonio;
    }

    public function setTestimonio(?string $testimonio): static
    {
        $this->testimonio = $testimonio;

        return $this;
    }
}

src/Entity/Empleado.php
<?php

namespace App\Entity;

use App\Entity\Categoria;
use App\Entity\Grupo;
use App\Entity\Usuario;
use App\Repository\EmpleadoRepository;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * Entidad que define los datos de los empleados de la plantilla actual de la US.
 * @author Ramón M. Gómez <ramongomez@us.es>
 */
#[ORM\Entity(repositoryClass: EmpleadoRepository::class)]
#[ORM\Table(name: 'plantilla_empleado')]
class Empleado
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    private ?int $id = null;

    #[ORM\OneToOne(targetEntity: Usuario::class)]
    private ?Usuario $usuario = null;



    #[ORM\ManyToOne(targetEntity: Categoria::class)]
    private ?Categoria $categoria = null;


    #[ORM\ManyToOne(targetEntity: Situacion::class)]
    private ?Situacion $situacion = null;


    #[ORM\ManyToOne(targetEntity: Grupo::class)]
    private ?Grupo $grupo = null;

    #[ORM\ManyToOne(targetEntity: Ausencia::class)]
    private ?Ausencia $ausencia = null;



    #[ORM\Column(type: Types::STRING, length: 50)]
    private ?string $nrp = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $nivel = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    private ?DateTimeInterface $vigente = null;

    #[ORM\ManyToOne(targetEntity: Empleado::class)]
    public ?Empleado $validador = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    public ?DateTimeInterface $cesado = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $consolidado = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    private ?DateTimeInterface $consolidacion = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $antiguedad = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $en_titular = null;

    #[ORM\Column(type: Types::SMALLINT, nullable: true)]
    private ?int $en_ocupada = null;

    #[ORMColumn(type: Types::STRING, length: 100)]
    private ?string $nombre = null;
    #[ORMColumn(type: Types::STRING, length: 100)]
    private ?string $apellido1 = null;
    #[ORMColumn(type: Types::STRING, length: 100, nullable: true)]
    private ?string $apellido2 = null;
    #[ORMColumn(type: Types::STRING, length: 11, nullable: true)]
    private ?string $doc_identidad = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->usuario;
    }

    public function setUsuario(?Usuario $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }





    public function getCategoria(): ?Categoria
    {
        return $this->categoria;
    }

    public function setCategoria(?Categoria $categoria): self
    {
        $this->categoria = $categoria;

        return $this;
    }



    public function getSituacion(): ?Situacion
    {
        return $this->situacion;
    }

    public function setSituacion(?Situacion $situacion): self
    {
        $this->situacion = $situacion;

        return $this;
    }



    public function getGrupo(): ?Grupo
    {
        return $this->grupo;
    }

    public function setGrupo(?Grupo $grupo): self
    {
        $this->grupo = $grupo;

        return $this;
    }

    public function getAusencia(): ?Ausencia
    {
        return $this->ausencia;
    }

    public function setAusencia(?Ausencia $ausencia): self
    {
        $this->ausencia = $ausencia;

        return $this;
    }





    public function getNrp(): ?string
    {
        return $this->nrp;
    }

    public function setNrp(?string $nrp): self
    {
        $this->nrp = $nrp;

        return $this;
    }

    public function getNivel(): ?int
    {
        return $this->nivel;
    }

    public function setNivel(?int $nivel): self
    {
        $this->nivel = $nivel;

        return $this;
    }

    public function getVigente(): ?DateTimeInterface
    {
        return $this->vigente;
    }

    public function setVigente(?DateTimeInterface $vigente): self
    {
        $this->vigente = $vigente;

        return $this;
    }

    public function getValidador(): ?Empleado
    {
        return $this->validador;
    }

    public function setValidador(?Empleado $empleado): self
    {
        $this->validador = $empleado;

        return $this;
    }

    public function getCesado(): ?DateTimeInterface
    {
        return $this->cesado;
    }

    public function setCesado(?DateTimeInterface $cesado): self
    {
        $this->cesado = $cesado;

        return $this;
    }

    public function getConsolidado(): ?int
    {
        return $this->consolidado;
    }

    public function setConsolidado(?int $consolidado): self
    {
        $this->consolidado = $consolidado;

        return $this;
    }

    public function getConsolidacion(): ?DateTimeInterface
    {
        return $this->consolidacion;
    }

    public function setConsolidacion(?DateTimeInterface $consolidacion): self
    {
        $this->consolidacion = $consolidacion;

        return $this;
    }

    public function getAntiguedad(): ?int
    {
        return $this->antiguedad;
    }

    public function setAntiguedad(?int $periodo): self
    {
        $this->antiguedad = $periodo;

        return $this;
    }

    public function getEnTitular(): ?int
    {
        return $this->en_titular;
    }

    public function setEnTitular(?int $periodo): self
    {
        $this->en_titular = $periodo;

        return $this;
    }

    public function getEnOcupada(): ?int
    {
        return $this->en_ocupada;
    }

    public function setEnOcupada(?int $periodo): self
    {
        $this->en_ocupada = $periodo;

        return $this;
    }
    public function __toString(): string
    {
        return trim(sprintf('%s %s %s', $this->nombre ?? '', $this->getApellido1() ?? '', $this->getApellido2() ?? ''));
    }
    public function getNombre(): ?string
    {
        return $this->nombre;
    }
    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }
    public function getApellido1(): ?string
    {
        return $this->apellido1;
    }
    public function setApellido1(string $apellido1): static
    {
        $this->apellido1 = $apellido1;

        return $this;
    }
    public function getApellido2(): ?string
    {
        return $this->apellido2;
    }
    public function setApellido2(?string $apellido2): static
    {
        $this->apellido2 = $apellido2;

        return $this;
    }
    public function getDocIdentidad(): ?string
    {
        return $this->doc_identidad;
    }
    public function setDocIdentidad(?string $doc_identidad): static
    {
        $this->doc_identidad = $doc_identidad;

        return $this;
    }

}

src/Form/Desempenyo/EvaluadorType.php
<?php

namespace App\Form\Desempenyo;

use App\Entity\Desempenyo\Evalua;
use App\Form\DataTransformer\EmpleadoDniTransformer;
use Override;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Formulario para reasignar un evaluador a un empleado.
 * @author Ramón M. Gómez <ramongomez@us.es>
 * @extends AbstractType<Evalua>
 */
class EvaluadorType extends AbstractType
{
    public function __construct(private readonly EmpleadoDniTransformer $empleadoDniTransformer) {
    }

    #[Override]
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $tipos = [
            'Responsable/Principal' => Evalua::EVALUA_RESPONSABLE,
            'Tercer agente' => Evalua::EVALUA_OTRO,
        ];
        /** @var Evalua $evalua */
        $evalua = $options['data'];
        $builder
            ->add('empleado', TextType::class, [
                'attr' => ['readonly' => true],
                'data' => $evalua->getEmpleado(),
                'mapped' => false,
            ])
            ->add('tipoEvaluador', ChoiceType::class, [
                'choices' => null === $evalua->getEmpleado() ? $tipos : array_filter($tipos, fn ($t) => $evalua->getTipoEvaluador() === $t),
                'label' => 'Tipo de Evaluador',
                'mapped' => false,
            ])
            ->add('evaluador', TextType::class, [
                'attr' => ['readonly' => true],
                'help' => 'Elegir un evaluador de la lista.',
                'required' => true,
            ])
        ;
        // Convertir empleado en documento para poder elegir usando una "datatable"
        $builder->get('evaluador')->addModelTransformer($this->empleadoDniTransformer);
    }

    #[Override]
    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Evalua::class,
        ]);
    }
}

templates/desempenyo/admin/evaluador/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<div class="linea-botones">
    <button id="guardar" class="btn btn-primary">
        <em class="fas fa-save"></em> {{ button_label|default('Guardar') }}
    </button>
</div>
{{ form_end(form) }}

templates/desempenyo/admin/evaluador/_form_evaluador.html.twig
{{ form_start(form) }}
{{ form_row(form.empleado) }}
{{ form_row(form.tipoEvaluador) }}
<div class="mb-3 row">
    {{ form_label(form.evaluador) }}
    <div class="col-sm-2 py-3 bg-secondary bg-opacity-25 border-start border-4 border-secondary">
        {{ form_widget(form.evaluador) }}
    </div>
    <div class="col-sm-7 py-3 bg-secondary bg-opacity-25">
        <table class="tabla-condensada" id="evaluadores">
            <thead class="cabecera-condensada">
            <tr>
                <th>Documento</th>
                <th>Nombre</th>
            </tr>
            </thead>
            <tbody>
            {% for empleado in empleados -%}
                {% if empleado.id != form.vars.value.empleado.id -%}
                    <tr id="{{ empleado.docIdentidad }}">
                        <td>{{ empleado.docIdentidad }}</td>
                        <td>{{ empleado }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
        {{ form_help(form.evaluador, {help_attr: {class: 'text-secondary'}}) }}
    </div>
</div>
<div class="linea-botones">
    <button id="guardar" class="btn btn-primary">
        <em class="fas fa-save"></em> {{ button_label|default('Guardar') }}
    </button>
</div>
{{ form_end(form) }}

templates/desempenyo/admin/evaluador/volcado.html.twig
{% extends 'desempenyo/admin/cuestionario/index.html.twig' %}

{% block content %}
    <div class="pagina-titulo">{{ titulo }}</div>

    <div class="container-fluid">
        Última carga de datos: {{ ultimo is defined ? ultimo|date('Y-m-d H:i:s') : 'sin fecha' }}
    </div>

    <div class="pagina-seccion">
        Volcado de datos de evaluación de
        {{ tipo == constant('App\\Entity\\Desempenyo\\Evalua::EVALUA_RESPONSABLE') ? 'responsables' : 'otros agentes'}}
    </div>
    <div class="alert alert-info">
        El volcado de datos actualizará todas las relaciones entre empleados y sus evaluadores de competencias,
        teniendo en cuenta que todas las personas deben pertenecer activamente a la plantilla actual de la Universidad
        de Sevilla.<br>
        Los datos se cargarán usando un <strong>fichero CSV</strong> que contenga al menos los siguientes campos
        separados por comas:<br>
        {{ campos|join(', ') }}
    </div>

    {{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="linea-botones">
        <button id="cargar" class="btn btn-primary my-4"><em class="fas fa-upload"></em> Cargar fichero</button>
    </div>
    {{ form_end(form) }}
{% endblock %}

{% block migas %}
    {{ parent() }}
    <li class="breadcrumb-item"><a href="{{ path('desempenyo_admin_cuestionario_index') }}">Cuestionarios</a></li>
    <li class="breadcrumb-item">
        <a href="{{ path('desempenyo_admin_cuestionario_show', {id: cuestionario.id}) }}">{{ cuestionario.codigo }}</a>
    </li>
{% endblock %}

{% block botones %}
{% endblock %}

{%  block modal %}
    {{- include('layout/_dialogo_confirmar.html.twig', {pregunta: '¿Cargar evaluadores de empleados?'}) }}
    {{- include('layout/_dialogo_cargar.html.twig', {mensaje: 'Cargando evaluadores', progreso: true}) }}
{% endblock %}

{% block js %}
    {{ parent() }}
    <script type="module">
        // Confirmar el volcado, mostrar progreso de carga y cerrar diálogo al finalizar
        const cargar = $('#cargar');
        const modalCarga = $('#modalCarga');
        cargar.on('click', function (e) {
            e.preventDefault();
            if (!$('#volcado_fichero_csv').val()) {
                dialogo.hide();
                return false;
            }
            document.querySelector('#modalConfirmaTexto').innerHTML = '<p>Se actualizarán los datos de evaluadores y empleados para la evaluación del '
                + 'desempeño de la plantilla.<p>'
                + '<p>El proceso de carga puede tardar un tiempo.</p>';
            document.querySelector('#modalConfirma').showModal();
        });
        $('#modalConfirmaAceptar').on('click', function () {
            modalCarga.fadeIn('fast');
            cargar.closest('form').submit();
        });
        $(window).on('unload', function () {
            modalCarga.hide();
        });
    </script>
{% endblock %}